### ISSUE TITLE
Implement function contract ckecker

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metaschema#22]
```js
const buyTickets = (
  event, // number, event id
  count, // number, ticket count
  address // string, delivery address
  // Returns: boolean, success status
) => {
  metaschema.guard({ event, count, address });
};
```

**Comment by SemenchenkoVitaliy** [comment]
Documentation generator was removed in https://github.com/metarhia/metaschema/pull/182 from [@metarhia/metaschema](https://github.com/metarhia/metaschema) and moved to [@metarhia/metadoc](https://github.com/metarhia/metadoc). As for the issue, it's  not longer relevant since comments style was changed starting from 734a63378906f7243a91addb4fc72dbd3ff5bb7c.
