### ISSUE TITLE
Bug in introspection: function contract parser

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metaschema#25]
If function have no description as of now will be parsed -1 arguments

**Comment by SemenchenkoVitaliy** [comment]
Documentation generator was removed in https://github.com/metarhia/metaschema/pull/182 from [@metarhia/metaschema](https://github.com/metarhia/metaschema) and moved to [@metarhia/metadoc](https://github.com/metarhia/metadoc). As for the issue, it's  not longer relevant since comments style was changed starting from 734a63378906f7243a91addb4fc72dbd3ff5bb7c.
